New aliases

diff --git a/shortcuts b/shortcuts
--- a/shortcuts
+++ b/shortcuts
@@ -1,4 +1,144 @@
-# My own alias:
+####################################################### USEFUL ALIASES ######################################################################################
+# Hack The Box Start
+export HTB_TOKEN=
+alias start_htb="python3 ~/zsh-aliases/htb.py"
+
+# List all the IPs on my interfaces:
+list_ips() {
+  ip a show scope global | awk '/^[0-9]+:/ { sub(/:/,"",$2); iface=$2 } /^[[:space:]]*inet / { split($2, a, "/"); print "[\033[96m" iface"\033[0m] "a[1] }'
+}
+
+# List directory with the path:
+ls_pwd() {
+  echo -e "[\e[96m`pwd`\e[0m]\e[34m" && ls && echo -en "\e[0m"
+}
+
+# Find seclist directory for other aliases:
+get_seclists_dir() {
+  local dir
+    if [ -d "/opt/seclists" ]; then
+        dir="/opt/seclists"
+    elif [ -d "/usr/share/seclists" ]; then
+        dir="/usr/share/seclists"
+    elif [ -n "$SECLISTS_PATH" ]; then
+        dir="$SECLISTS_PATH"
+    else
+        echo "Error: Could not find SecLists directory. Please set SECLISTS_PATH environment variable or install SecLists in a standard location." >&2
+        return 1
+    fi
+    echo $dir
+    return 0
+}
+
+addhost() {
+    if [ "$#" -ne 2 ]; then
+      echo "[i] Usage: addhost <ip> <hostname>"
+      return 1
+    fi
+
+    ip="$1"
+    hostname="$2"
+    if grep -q "^$ip" /etc/hosts; then
+      sudo sed -i "/^$ip/s/$/ $hostname/" /etc/hosts
+      echo "[+] Appended $hostname to existing entry for $ip in /etc/hosts"
+    else
+      echo "$ip $hostname" | sudo tee -a /etc/hosts > /dev/null
+      echo "[+] Added new entry: $ip $hostname to /etc/hosts"
+    fi
+
+    grep "^$ip" /etc/hosts
+}
+#######################################################################################################################################################
+
+##################################################### PORT SCANNING ##################################################################################
+
+# TCP Scan
+nmap_tcp () {
+  if [ $# -eq 0 ]
+    then
+      echo "[i] Usage: nmap_default ip (options)"
+    else
+      [ ! -d "./nmap" ] && echo "[i] Creating $(pwd)/nmap..." && mkdir nmap
+      sudo nmap -n -Pn -sVC --open -p- --min-rate=10000 "${@}" -vv -oA nmap/tcp_default
+  fi
+}
+
+# UDP Scan
+nmap_udp () {
+  if [ $# -eq 0 ]
+    then
+      echo "[i] Usage: nmap_udp ip (options)"
+    else
+      [ ! -d "./nmap" ] && echo "[i] Creating $(pwd)/nmap..." && mkdir nmap
+      sudo nmap -n -Pn -sU -p- --min-rate=10000 "${@}" -vv -oA nmap/udp_default
+  fi
+}
+#######################################################################################################################################################
+
+#################################################### WEB SERVER ENUMERATION ##########################################################################
+
+# Directory Enumeration
+fuzz_dir() {
+    if [ "$#" -lt 1 ]; then
+        echo "[i] Usage: fuzz_dir <url> [-w <wordlist>] [ffuf options]"
+        return 1
+    fi
+
+    local url="$1"
+    shift
+
+    local seclists_dir
+    seclists_dir=$(get_seclists_dir)
+    local exit_status=$?
+    if [[ $exit_status -ne 0 ]]; then
+        return 1
+    fi
+
+    local default_wordlist="$seclists_dir/Discovery/Web-Content/raft-large-directories.txt"
+    local wordlist="$default_wordlist"
+    local ffuf_args=()
+
+    # Parse arguments
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+            -w)
+                wordlist="$2"
+                shift 2
+                ;;
+            *)
+                ffuf_args+=("$1")
+                shift
+                ;;
+        esac
+    done
+
+    ffuf -u "$url/FUZZ" -w "$wordlist" -e .php,.asp,.txt,.php.old,.html,.php.bak,.bak,.aspx "${ffuf_args[@]}"
+}
+
+# VHOST Enumeration
+vhost() {
+    if [ "$#" -lt 1 ]; then
+        echo "[i] Usage: vhost <domain> (extra arguments)"
+        return 1
+    fi
+
+    local seclists_dir
+    seclists_dir=$(get_seclists_dir)
+    local exit_status=$?
+    if [[ $exit_status -ne 0 ]]; then
+        return 1
+    fi
+
+    local url=$1
+    # Default to http if no protocol specified, but allow optional specifying of the protocol
+    # So we can also use it against HTTPS
+    if [[ ! "$url" =~ ^https?:// ]]; then
+        url="http://$url"
+    fi
+
+    local wordlist="$seclists_dir/Discovery/DNS/bitquark-subdomains-top100000.txt"
+    ffuf -H "Host: FUZZ.$1" -u $url -w "$wordlist" "${@:2}"
+}
 
 # Start provisional web server to have access to my tools:
 webserver() {
@@ -34,7 +174,7 @@ webserver() {
 
     # Start the Python HTTP server
     echo "Starting HTTP server on port $port, serving directory $directory"
-    python3 -m http.server -d "$directory" "$port" &
+    sudo python3 -m http.server -d "$directory" "$port" &
 
     # Keep the prompt open for additional commands
     while true; do
@@ -112,7 +252,7 @@ smbserver() {
         echo -E "- copy sam.save \\\\$IP\share\ "
         echo -E "- robocopy \\\\$IP\share\\netcat .\ nc.exe"
         echo "########################################################"
-impacket-smbserver share $1 -smb2support -user david -password david
+sudo smbserver.py share $1 -smb2support -user david -password david
 }
 
 gitdump() {
